### ISSUE TITLE
Missing config file makes it hard to puzzle out the URL for station_url the Amazon S3 bucket.

### ISSUE THREAD

**Issue by clockwatching** [spetykowski/ldn-departures-board#8]
You've got your config.py (quite smartly!) excluded from check. Puzzling through the app_id and app_name settings was easy... but it took a while to figure out the third missing variable in the config was a URL for an amazon S3 bucket where you're pulling station info. That one I couldn't puzzle out.

This project looks cool, and I was interested because it uses the public TFL api. A few months back transportapi.com that Hutchinson uses switched the free accounts from 1000 queries per day to 30, so its sadly kinda useless.

**Comment by petykowski** [comment]
Hi @clockwatching. The third parameter in the config file is a URL to a .txt file on AWS which stores a JSON string with the parameters, `station`, `direction`, and  `updated_on`. An example of the file is as follows:

`{"station": "Seven Sisters", "direction": "Inbound", "updated_on": "2022-06-20T23:45:16+01:00"}`

I keep this information in a S3 bucket so that I can change the station that is displayed on the arrival board via API call.

I hope this helps!

**Comment by petykowski** [comment]
Merged commit https://github.com/petykowski/London-TFL-Arrivals-Board/commit/d83c807ba08677d0a8766ff9a7b65627d2508b11 with an updated `README.md` file containing details about the `station.txt` and `config.py`.
